### ISSUE TITLE
Enabling wiki

### ISSUE THREAD

**Issue by carltondickson** [Nearsoft/php-selenium-client#1]
Is it possible to enable the wiki for this project, even it's purely for examples supplied by the community...perhaps linking out to snippets at https://gist.github.com
I have a basic test using click that isn't working and this is a barrier to me using these bindings at the moment, once I resolve the issue I would like to be able to share my solution/learnings for others.

**Comment by carltondickson** [comment]
I think I found the solution to my click problem, and I'm relieved I can get on with testing now.

I ran your demos and noticed no alert boxes popped up which made me wonder if Norton Internet Security 2011 was interfering. I uninstalled Norton and tried mine and your tests and it turns out it was the cause of the problem all along.

Closest thing I could find to my issue is in these threads...but I think that is more to do with downloading Selenium

http://code.google.com/p/selenium/issues/detail?id=721
https://groups.google.com/group/webdriver/browse_thread/thread/12f4f210f61c8711

**Comment by polosantiago** [comment]
@carltondickson thanks for your suggestion about the wiki, it will definitively be of help! It has just been created

**Comment by polosantiago** [comment]
i'm glad you found a solution for the antivirus interference problem. I didn't run into it myself. Thanks for sharing your experience

**Comment by carltondickson** [comment]
Thanks
