### ISSUE TITLE
Close brower when done

### ISSUE THREAD

**Issue by joshribakoff** [Nearsoft/php-selenium-client#24]
Cool library. It leaves the browser open when its done, would be nice to auto close.

**Comment by polosantiago** [comment]
Thanks for your comment - Closing the browser requires an http request to be sent to the selenium server API. When your php flow ends, the PHP-SeleniumClient flow ends too. Not sure there is something we can do in within the library.

You could have a deamon detecting lingering selenium sessions opened and  close the browser by killing those sessions

What I tend to do is have an abstract class from which all test inherit and call WebDriver::quit() in a common spot where the test ends. I.e. in tearDown method for tests of type PHPUnit_Framework_TestCase. That way I don't have to worry about closing the browser every time.

**Comment by joshribakoff** [comment]
I see, I have no problem calling WebDriver::quit() manually, I didn't know that existed.
