### ISSUE TITLE
webElementSendKeys doesn't handle multi-byte strings correctly 

### ISSUE THREAD

**Issue by roninbar** [Nearsoft/php-selenium-client#6]
When a multi-byte string is passed to webElementSendKeys, it gets split into individual bytes instead of  multi-byte characters. For example, when I tried to type my name in Hebrew which is "רון",  WebDriver tried to send it as six invalid characters.

**Comment by yair27** [comment]
Hi, it seems that this bug it's been fixed by @nenadalm and it's been merge into the master branch of the project

**Comment by roninbar** [comment]
Thanks! I added a test for this. If you'd like, I can upload it to my branch.

**Comment by yair27** [comment]
Can you merge that test into the master branch of the main Project https://github.com/Nearsoft/PHP-SeleniumClient

Create a pull request and I will accept

**Comment by roninbar** [comment]
I need some time to learn how to use GitHub. :( In the mean time, here's the code. You can just copy and paste it into WebElementTest.php:

```
    /**
     * @group evento-additions
     */
public function testSendKeysShouldRetrieveHebrewText()
{
    $textarea1 = $this->_driver->findElement(By::id("txtArea1"));
    $textarea1->sendKeys("חיפה 34557");
    $this->assertEquals("חיפה 34557", $textarea1->getAttribute("value"));
}
```

**Comment by nenadalm** [comment]
There is explanation how to use pull requests: https://help.github.com/articles/using-pull-requests

**Comment by roninbar** [comment]
Thanks for the article. It was very helpful!
